[phases.setup]
nixPkgs = ["nodejs-20_x"]

[phases.install]
cmds = ["npm install --omit=dev --legacy-peer-deps --no-audit --no-fund"]

[phases.build]
cmds = ["npm run build:railway"]

[start]
cmd = "npm start"